server:
  port: 5000
spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://124.251.115.187:3306/trip?useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
        username: trip
        password: _1428tetr
        driverClassName: com.mysql.jdbc.Driver
        idleTimeout: 60000
        connectionTimeout: 60000
        maxLifetime: 300000
        minimumIdle: 2
        maximumPoolSize: 16
        dataSourceProperties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
    props:
      sql.show: true
      executor.size: 512
    sharding:
      default-data-source-name: ds0
      tables:
        trip_message:
          logic-table: trip_message
          key-generator:
            type: SNOWFLAKE
            column: mid
            props:
              worker.id: 123
          table-strategy:
            standard:
              sharding-column: tkey
              precise-algorithm-class-name: com.sharding.algorithm.TripMessageShardingAlgorithm
          actual-data-nodes: ds0.trip_message_$->{2018..2022}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}$->{['','0','1','2','3']}$->{['','0','1','2','3','4','5','6','7','8','9']}
mybatis:
  configuration:
    database-id: ds0
    map-underscore-to-camel-case: true
  type-aliases-package: com.sharding.entity
  mapper-locations:
  - classpath*:mapper/*.xml